# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Samuel Grave
author-title: Full Stack Developer
email: samuel.grave.silva@outlook.com
twitter: sammaelmh
github: samuelgrave
facebook: sammaelmh
linkedin: samuel.grave.silva/en
bio: "Father. Brazilian developer. Game, music, beer and technology lover.
      My first steps with development began at age 13, with creation of websites. In 2002 I met C#, and then I worked in several projects, focusing on web development.
      In the last 8 years I am in the formal market as a developer.
      I am passionate about technology and always seek new and better ways to solve problems. 
      Enthusiast for agile methodologies, already realized projects with SCRUM, XP and attended some workshops with Kanban.
      I like to work with both: Front-End and Back-End development. I work with many languages, frameworks and technologies"

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 4
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 3
  - name: jQuery
    level: 3
  - name: Angular
    level: 2
  - name: Bootstrap
    level: 3
  - name: Materialize CSS
    level: 1
  - name: LESS
    level: 1
  - name: SASS
    level: 1

back-end:
  - name: C#
    level: 5
  - name: Node.js
    level: 2
  - name: Python
    level: 2
  - name: Java
    level: 3
  - name: SQL
    level: 4

mobile:
  - name: Xamarin
    level: 3

db:
  - name: MySQL
    level: 3
  - name: PostgreSQL
    level: 3
  - name: MongoDB
    level: 2
  - name: SQL Server
    level: 4
  - name: Oracle
    level: 3
  - name: NoSQL
    level: 2

devops:
  - name: Docker
    level: 1
  - name: Git
    level: 3
  - name: Continuous Integration
    level: 3
  - name: Continuous Delivery
    level: 2

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 4

others:
  - name: Web Services
    level: 5
  - name: REST
    level: 4
  - name: EntityFramework
    level: 3
  - name: MEAN Stack
    level: 3

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
